[env]
_.python.venv = { path = ".venv", create = false }

[tasks.bump]
description = "Bump the python package version. Takes one argument: `major`, `minor` or `patch`."
run = """
#!/usr/bin/env bash

v="$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)"
uvx --from bump2version bumpversion --allow-dirty --current-version "$v" "$1" pyproject.toml
"""
