name: Update Plots

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures history is checked out

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # Specify your Python version here

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            type1cm
            siunitx
            type1ec
            underscore
            times
            dvipng

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock  # Assuming dependencies are listed here

      - name: Generate plots
        run: |
          python ./examples/example.py

      - name: Commit and push plots
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -f ./examples/figures/*.png  # Force add the plots even if ignored
          git commit -m "Update plots" || exit 0  # Exit gracefully if no changes
          git push origin HEAD:refs/heads/temporary-branch-for-plots

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: temporary-branch-for-plots
          base: release # Target branch
          title: Update generated plots
          body: This PR updates the generated plots.
          delete-branch: true # Deletes the temporary branch after merge
